README.md, build.sbt, version.sbt
=> Confluent Platform 5.1.0

build.sbt
See embeddedkafka/embedded-kafka#20.
=> Redefine release process

src/main/scala/net.manub.embeddedkafka/schemaregistry/config.scala, src/test/scala/net/manub/embeddedkafka/schemaregistry/EmbeddedKafkaSpec.scala
=> fix EmbeddedKafkaConfig.defaultConfig declared type

build.sbt
...and Confluent Platform 5.2.0
=> Upgrade to Kafka 2.2.0

src/main/scala/net.manub.embeddedkafka/schemaregistry/EmbeddedKafka.scala, src/main/scala/net.manub.embeddedkafka/schemaregistry/avro/Codecs.scala, src/main/scala/net.manub.embeddedkafka/schemaregistry/config.scala, src/main/scala/net.manub.embeddedkafka/schemaregistry/ops/SchemaRegistryOps.scala, src/main/scala/net.manub.embeddedkafka/schemaregistry/package.scala, src/main/scala/net.manub.embeddedkafka/schemaregistry/streams/EmbeddedStreamsConfigImpl.scala, src/test/scala/net/manub/embeddedkafka/schemaregistry/EmbeddedKafkaTraitSpec.scala, src/test/scala/net/manub/embeddedkafka/schemaregistry/streams/ExampleKafkaStreamsSpec.scala
=> Add support for GenericRecord Serde and Avro Schema Compatibility config

.travis.yml, build.sbt
To fix TravisCI build problems as per travis-ci/travis-ci#10290
=> switch to openjdk8

build.sbt, project/Dependencies.scala, project/plugins.sbt
apply scalafmt to sbt files as well
=> refactor build.sbt, add Dependencies.scala

embedded-kafka-schema-registry/src/main/scala/net.manub.embeddedkafka/schemaregistry/EmbeddedKafka.scala, project/Dependencies.scala
refactor after semi-private method removal
=> bump embeddedkafka version to 2.5.1

embedded-kafka-schema-registry/src/main/scala/net.manub.embeddedkafka/schemaregistry/servers.scala, project/Dependencies.scala
=> bump Scala versions

project/Dependencies.scala
bump embedded-kafka version to 2.6.0
=> bump CP version to 6.0.0

project/Dependencies.scala
bump Scala versions to match Kafka's
=> bump embedded-kafka version to 2.7.0

.github/mergify.yml, .github/workflows/coverage-report.yml, .github/workflows/release.yml, .github/workflows/test.yml
also prevent undesired scala-library version bump
=> fix mergify conditions

build.sbt
=> use coverageMinimumStmtTotal

embedded-kafka-schema-registry/src/main/scala/io/github/embeddedkafka/schemaregistry/ops/SchemaRegistryOps.scala
=> definitely fix ambiguous reference to overloaded definition

.github/workflows/coverage-report.yml, .github/workflows/release.yml, .github/workflows/test.yml
=> update test workflow to use setup-java action

project/Dependencies.scala
See https://github.com/embeddedkafka/embedded-kafka/pull/416
=> replace slf4j-log4j12 with slf4j-reload4j

README.md, build.sbt, embedded-kafka-schema-registry/src/main/scala/io/github/embeddedkafka/schemaregistry/EmbeddedKafka.scala, project/Dependencies.scala
Waiting for Confluent to release v7.4.0
=> cross-compile project for Scala 3

.github/dependabot.yml
See discussion [here](https://github.com/embeddedkafka/embedded-kafka/pull/466#issuecomment-1709937429)
=> add slf4j-reload4j to dependabot ignore list

.github/workflows/coverage-report.yml, .github/workflows/release.yml, .github/workflows/test.yml
See https://github.com/actions/runner-images/issues/11350
=> add setup-sbt step to fix workflows on ubuntu-24.04

build.sbt
Resolves https://github.com/embeddedkafka/embedded-kafka/issues/569
=> build: publish to Sonatype Central
